[versions]
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.9.3"
androidx-appcompat = "1.7.1"
androidx-core = "1.13.1"
androidx-espresso = "3.6.1"
androidx-lifecycle = "2.8.4"
androidx-testExt = "1.2.1"
composeHotReload = "1.0.0-rc02"
junit = "4.13.2"
kotlinx-coroutines = "1.9.0"
kotlin = "2.1.0"
composeMultiplatform = "1.7.1"


ktor_version = "3.0.1"
kotlinx-datetime = "0.6.1"
kotlinxSerialization = "1.7.3"
kotlinx-io-core = "0.5.4"


room = "2.7.0-alpha11"
sqlite = "2.5.0-alpha11"
kspVersion = "2.1.0-1.0.29"

navigation-compose = "2.8.0-alpha10"

data-store = "1.1.1"
data-store-preferences = "1.1.1"

kamel = "1.0.0"

slf4j = "2.0.9"

# KOIN
koin = "4.0.0"
koin-compose-multiplatform = "4.0.0"


[libraries]


kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

#ktor

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor_version" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor_version" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor_version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor_version" }

#datetime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

#io

kotlinx-io = {module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io-core" }

#serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

#room
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }


navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

data-store = { module = "androidx.datastore:datastore", version.ref = "data-store" }
data-store-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "data-store-preferences" }



kamel-image-default = { module = "media.kamel:kamel-image-default", version.ref = "kamel" }

ui-window = { module = "org.jetbrains.compose.ui:ui-window", version.ref = "composeMultiplatform" }

# KOIN
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose-multiplatform" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose-multiplatform" }

# SLF4J
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }


[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

#serialization
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

#room
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
androidx-room = { id = "androidx.room", version.ref = "room" }
